/**
 * Messages API call for one payer key. One payer per invocation.
 *
 * Everything here is load-bearing for correctness rather than style, and each
 * piece was established by a live probe rather than from the docs alone:
 *
 *  - THREE stop reasons, not two. `end_turn`, `pause_turn` (resend unchanged),
 *    and `tool_use`. Because `emit_findings` is a client tool and web_search is a
 *    server tool, the API returns `tool_use` and defers the search when both land
 *    in one parallel group, so every healthy run is multi-turn. Treating any of
 *    the three as terminal is a silent-truncation bug.
 *  - Assistant content is echoed back BYTE-IDENTICAL: the same parsed array, never
 *    filtered or rebuilt. Thinking blocks (Opus 5 emits them unrequested),
 *    server_tool_use blocks, and web_search results with their `encrypted_content`
 *    must round-trip exactly or the resend 400s.
 *  - `container` is REQUIRED to continue. Dynamic filtering runs web_search inside
 *    an auto-provisioned code-execution container; without reattaching, turn 2
 *    returns 400 "container_id is required when there are pending tool uses
 *    generated by code execution with tools." This happens even though we never
 *    declare code_execution ourselves.
 *  - Search/fetch errors return HTTP 200 with `content` as a single error OBJECT
 *    rather than a LIST. Under dynamic filtering those error blocks may never
 *    surface at all (nested results come back encrypted), so run health must NOT
 *    depend on seeing them — hence the emit-never-called and zero-search gates.
 *
 * No secrets are logged. The API key is passed to the transport and never printed,
 * and no URL with query parameters is logged.
 */

import { matchesAnyDomain, rosterEntry, type RosterEntry } from './roster.js';
import type { EmitFindingsPayload, ResearchResult, RetrievedUrl, TokenUsage } from './types.js';
import { CHANGE_TYPES, CONFIDENCES, ORIGINATORS, SCOPES, UNREACHABLE_REASON_CODES } from './types.js';

export const MODEL = 'claude-opus-5';
export const MAX_TOKENS = 32_000;
export const TURN_BUDGET = 12;
export const WEB_SEARCH_TOOL = 'web_search_20260318';
export const WEB_FETCH_TOOL = 'web_fetch_20260318';
/** Bounds text content per fetch. Documented NOT to bound PDFs, so fetchUses is
 *  the real cost ceiling. */
export const MAX_FETCH_CONTENT_TOKENS = 30_000;

/** Injected so tests are hermetic — no live API in `npm test`. */
export interface MessagesTransport {
  (payload: unknown): Promise<{ status: number; body: string }>;
}

export interface ResearchOptions {
  payerKey: string;
  windowStart: string;
  windowEnd: string;
  /** Identity lines for findings already reported, so the model suppresses them.
   *  Empty on a first run. */
  priorState?: string[];
  focus: string;
  transport: MessagesTransport;
  now?: () => number;
}

const strField = (description: string) => ({ type: 'string', description });

export const EMIT_FINDINGS_TOOL = {
  name: 'emit_findings',
  strict: true,
  description: 'Emit structured policy findings. Call exactly once, after all searching is complete.',
  input_schema: {
    type: 'object',
    additionalProperties: false,
    required: ['findings', 'checked_no_change', 'unreachable'],
    properties: {
      findings: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: [
            'payer_plan', 'change_type', 'originator', 'summary', 'codes_affected',
            'scope', 'self_funded_relevant', 'date_published', 'date_approved',
            'date_effective', 'source_url', 'source_domain', 'confidence', 'embed_text',
          ],
          properties: {
            payer_plan: strField('Payer and, where applicable, the specific plan or product line.'),
            change_type: { type: 'string', enum: [...CHANGE_TYPES] },
            originator: { type: 'string', enum: [...ORIGINATORS] },
            summary: strField('What changed, in one or two plain sentences.'),
            codes_affected: { type: 'array', items: { type: 'string' } },
            scope: { type: 'string', enum: [...SCOPES] },
            self_funded_relevant: { type: 'boolean' },
            date_published: strField('Date posted/announced/bulletined, YYYY-MM-DD. THIS is the window filter. "unknown" if not establishable — never infer from the effective date.'),
            date_approved: strField('Internal approval date, YYYY-MM-DD, or "unknown".'),
            date_effective: strField('Operative claims date, YYYY-MM-DD, or "unknown".'),
            source_url: strField('A URL actually retrieved or fetched this session. Never reconstructed.'),
            source_domain: strField('Registrable domain of source_url.'),
            // source_tier is absent by design: derived at ingest from the domain map.
            confidence: { type: 'string', enum: [...CONFIDENCES] },
            embed_text: strField('Self-contained paragraph naming payer, change, codes, and dates. No pronouns referring to other findings.'),
          },
        },
      },
      checked_no_change: { type: 'array', items: { type: 'string' } },
      unreachable: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['payer', 'reason_code', 'reason', 'url'],
          properties: {
            payer: strField('Payer name.'),
            reason_code: { type: 'string', enum: [...UNREACHABLE_REASON_CODES] },
            reason: strField('Specific detail behind the reason_code.'),
            url: strField('URL attempted, or "none".'),
          },
        },
      },
    },
  },
} as const;

export function buildTools(entry: RosterEntry): unknown[] {
  return [
    {
      type: WEB_SEARCH_TOOL,
      name: 'web_search',
      max_uses: entry.searchUses,
      // 'full', never 'excluded': the retrieved-URL set IS the provenance gate, and
      // 'excluded' removes the web_search_tool_result blocks that carry it.
      response_inclusion: 'full',
      allowed_domains: entry.domains,
    },
    {
      type: WEB_FETCH_TOOL,
      name: 'web_fetch',
      max_uses: entry.fetchUses,
      response_inclusion: 'full',
      // Same domain map as search: a fetch must not escape the payer's scope.
      allowed_domains: entry.domains,
      max_content_tokens: MAX_FETCH_CONTENT_TOKENS,
    },
    EMIT_FINDINGS_TOOL,
  ];
}

function emptyPayload(): EmitFindingsPayload {
  return { findings: [], checked_no_change: [], unreachable: [] };
}

/** Union rather than error: a second emit is an anomaly to log, not a failure. */
function unionPayloads(calls: EmitFindingsPayload[]): EmitFindingsPayload {
  return calls.reduce<EmitFindingsPayload>((acc, call) => ({
    findings: [...acc.findings, ...(call?.findings ?? [])],
    checked_no_change: [...acc.checked_no_change, ...(call?.checked_no_change ?? [])],
    unreachable: [...acc.unreachable, ...(call?.unreachable ?? [])],
  }), emptyPayload());
}

interface Harvested {
  urls: RetrievedUrl[];
  toolErrors: string[];
  emitCalls: EmitFindingsPayload[];
}

/** Walks content blocks, including code-execution results (dynamic filtering nests
 *  search/fetch pairs inside them). A FETCHED url is a retrieved url: it joins the
 *  provenance set and faces the domain gate exactly like a searched one. */
export function harvestBlocks(blocks: unknown[]): Harvested {
  const out: Harvested = { urls: [], toolErrors: [], emitCalls: [] };
  const walk = (list: unknown[]): void => {
    for (const raw of list ?? []) {
      const block = raw as Record<string, any>;
      if (!block || typeof block !== 'object') continue;

      if (block.type === 'web_search_tool_result') {
        // LIST => results. Single OBJECT => error.
        if (Array.isArray(block.content)) {
          for (const result of block.content) {
            if (result?.url) out.urls.push({ url: String(result.url), via: 'search' });
          }
        } else if (block.content) {
          out.toolErrors.push(`web_search:${block.content.error_code ?? 'unknown_error'}`);
        }
      }

      if (block.type === 'web_fetch_tool_result') {
        const content = block.content;
        if (content?.type === 'web_fetch_result' && content.url) {
          out.urls.push({ url: String(content.url), via: 'fetch' });
        } else if (content?.type === 'web_fetch_tool_result_error') {
          out.toolErrors.push(`web_fetch:${content.error_code ?? 'unknown_error'}`);
        }
      }

      if (block.type === 'code_execution_tool_result' && Array.isArray(block.content)) {
        walk(block.content);
      }

      if (block.type === 'tool_use' && block.name === 'emit_findings') {
        out.emitCalls.push(block.input as EmitFindingsPayload);
      }
    }
  };
  walk(blocks);
  return out;
}

export function buildUserMessage(opts: ResearchOptions, entry: RosterEntry): string {
  const prior = opts.priorState?.length
    ? `(${opts.priorState.length} already reported, do NOT re-report these)\n${opts.priorState.join('\n')}`
    : '(none — first run)';
  return [
    `RUN DATE: ${opts.windowEnd}`,
    `LAST_DATE: ${opts.windowStart}`,
    `RESEARCH WINDOW: ${opts.windowStart} → ${opts.windowEnd}`,
    'WINDOW FILTER: publication date (see the WINDOW RULE in your instructions)',
    '',
    'PAYER IN SCOPE (this run covers this payer and no other):',
    entry.display,
    '',
    'PRIOR STATE (do not re-report these as new):',
    prior,
    '',
    'FOCUS THIS RUN:',
    opts.focus,
    '',
    'Research and emit findings.',
  ].join('\n');
}

/**
 * Runs one payer key to completion and reports what happened. Never throws for a
 * research outcome — a bad run comes back with `failures` populated so the caller
 * can persist a FAILED run row rather than losing the diagnostics.
 */
export async function researchPayer(
  opts: ResearchOptions,
  systemPrompt: string,
): Promise<ResearchResult> {
  const entry = rosterEntry(opts.payerKey);
  if (!entry) throw new Error(`Unknown payer key: ${opts.payerKey}`);

  const clock = opts.now ?? Date.now;
  const startedAt = clock();
  const tools = buildTools(entry);
  const messages: Array<{ role: string; content: unknown }> = [
    { role: 'user', content: buildUserMessage(opts, entry) },
  ];

  const urls: RetrievedUrl[] = [];
  const toolErrors: string[] = [];
  const emitCalls: EmitFindingsPayload[] = [];
  const usages: TokenUsage[] = [];
  let searchRequests = 0;
  let fetchRequests = 0;
  let turnCount = 0;
  let stopReason = '';
  let containerId: string | null = null;
  let transportFailure: string | null = null;
  let turnBudgetExceeded = false;

  for (;;) {
    if (turnCount >= TURN_BUDGET) {
      turnBudgetExceeded = true;
      break;
    }
    turnCount += 1;

    const request: Record<string, unknown> = {
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: systemPrompt,
      tools,
      messages,
    };
    if (containerId) request.container = containerId;

    const { status, body } = await opts.transport(request);
    if (status !== 200) {
      // Recorded, not thrown: the caller must still be able to persist a FAILED
      // run. Only the API's own message is surfaced, never the request.
      let detail = '';
      try {
        detail = String(JSON.parse(body)?.error?.message ?? '');
      } catch {
        detail = 'unparseable error body';
      }
      transportFailure = `HTTP ${status} on turn ${turnCount} — ${detail}`;
      break;
    }

    const message = JSON.parse(body) as Record<string, any>;
    usages.push(message.usage ?? {});
    searchRequests += message.usage?.server_tool_use?.web_search_requests ?? 0;
    fetchRequests += message.usage?.server_tool_use?.web_fetch_requests ?? 0;
    stopReason = String(message.stop_reason ?? '');
    if (message.container?.id) containerId = String(message.container.id);

    const harvested = harvestBlocks(message.content ?? []);
    urls.push(...harvested.urls);
    toolErrors.push(...harvested.toolErrors);
    emitCalls.push(...harvested.emitCalls);

    if (stopReason === 'end_turn') break;

    if (stopReason === 'pause_turn') {
      // Byte-identical: the same parsed array, untouched.
      messages.push({ role: 'assistant', content: message.content });
      continue;
    }

    if (stopReason === 'tool_use') {
      messages.push({ role: 'assistant', content: message.content });
      const results = (message.content as Array<Record<string, any>>)
        .filter((block) => block?.type === 'tool_use')
        .map((block) => ({ type: 'tool_result', tool_use_id: block.id, content: 'recorded' }));
      messages.push({ role: 'user', content: results });
      continue;
    }

    break; // max_tokens, or anything unrecognised
  }

  const payload = emitCalls.length ? unionPayloads(emitCalls) : null;
  const anomalies: string[] = [];
  if (emitCalls.length > 1) {
    anomalies.push(`emit_findings called ${emitCalls.length} times — unioned`);
  }

  // Dedupe by URL, keeping the first tool that surfaced it.
  const seen = new Map<string, RetrievedUrl>();
  for (const item of urls) if (!seen.has(item.url)) seen.set(item.url, item);
  // GATE D(2) — PER-URL EXCLUSION, not a run failure (Alec's ruling 2026-08-04,
  // supersedes fail-closed). `allowed_domains` is not strictly honored upstream:
  // web_fetch escaped it in ~11% of measured key-runs (a fixed arXiv/medRxiv/NCBI
  // set), and failing the whole run discarded ~97 good URLs' research each time.
  // Excluding the escaped URL BEFORE the provenance set is built means a finding
  // citing it fails resolveStatus and QUARANTINES via the ordinary path — it can
  // never be legitimized — while the run passes on its legitimate retrievals.
  // Exclusion runs before gates C and D(1), so a run whose EVERY retrieval
  // escaped ends with an empty legitimate set and still fails closed via D(1).
  const retrievedVia: RetrievedUrl[] = [];
  const domainEscapes: RetrievedUrl[] = [];
  for (const item of seen.values()) {
    (matchesAnyDomain(item.url, entry.domains) ? retrievedVia : domainEscapes).push(item);
  }
  const dedupedUrls = retrievedVia.map((item) => item.url);
  const failures: string[] = [];
  if (transportFailure) failures.push(`TRANSPORT — ${transportFailure}`);
  if (turnBudgetExceeded) failures.push(`TURN BUDGET (${TURN_BUDGET}) EXCEEDED`);
  // GATE A: a well-formed end_turn that never emitted is the exact bug this whole
  // design guards against. It is FAILED, not "no findings".
  if (emitCalls.length === 0) failures.push('GATE A — emit_findings never called');
  // GATE B: zero searches means nothing was researched. Also the only reliable
  // signal of an all-errored run, since error blocks may never surface.
  if (searchRequests === 0) failures.push('GATE B — web_search_requests === 0');
  // GATE C: findings asserting sources with no retrieved set at all.
  if (dedupedUrls.length === 0 && (payload?.findings ?? []).some((f) => f?.source_url)) {
    failures.push('GATE C — retrieved-URL set empty while findings assert source_urls');
  }
  // GATE D(1): nothing may mask a key whose own sources returned nothing. Still a
  // full-run failure — per-URL exclusion applies only to D(2) domain escapes.
  if (dedupedUrls.length === 0) {
    failures.push("GATE D — zero retrieved URLs (this key's own sources returned nothing)");
  }
  // GATE E: max_tokens mid-emit_findings yields a truncated strict-tool input that
  // parses as valid JSON but is not the whole payload. A healthy turn 1 ends on
  // tool_use.
  if (stopReason === 'max_tokens') {
    failures.push('GATE E — stop_reason max_tokens (truncated strict-tool input)');
  }

  // Loud, one line per escaped URL: url + admitting tool + the allow-list it
  // escaped. These are public bulletin/preprint URLs — non-PHI by construction.
  for (const escaped of domainEscapes) {
    anomalies.push(
      `GATE D VIOLATION — ${escaped.url} (via ${escaped.via}) outside allowed_domains ` +
      `[${entry.domains.join(', ')}] — excluded from retrieved set`,
    );
  }

  return {
    payload,
    retrievedUrls: dedupedUrls,
    retrievedVia,
    domainEscapes,
    toolErrors,
    searchRequests,
    fetchRequests,
    turnCount,
    stopReason,
    usages,
    emitCallCount: emitCalls.length,
    failures,
    anomalies,
    wallMs: clock() - startedAt,
  };
}
