-- 0081 ROLLBACK — drop the four trigram GIN search indexes from the charge rollup.
--
-- ⚠ Same apply path as 0081 forward: DROP INDEX CONCURRENTLY cannot run inside a transaction
--   block — run each statement as its own single-statement autocommit query (Supabase MCP
--   execute_sql), never via apply_migration. (Plain DROP INDEX would also work but takes an
--   ACCESS EXCLUSIVE lock on the matview, blocking readers for the drop's duration.)
--
-- Search behavior after rollback: `ilike` degrades gracefully to the pre-0081 seq scan —
-- slower, not broken. No code revert is required (the ::text-cast removal is index-agnostic).

-- The executable rollback statements live in
-- 0081_cmd_charge_rollup_search_trgm_rollback.manual.sql.
-- This numbered file is intentionally comment-only for transactional runners.
