-- 0114 ROLLBACK — restore the cluster statement_timeout for cmd_rollup_writer_login, and put the
-- trigram index back.
--
-- ⚠ ROLLING THIS BACK RE-BREAKS THE HOURLY REFRESH. `reset` drops the role back to the cluster-wide
-- 120s (source = configuration file), and the refresh averaged 108.5s and rising when 0114 was
-- written — so the :45 cron returns to failing intermittently, and then permanently as it grows.
-- Roll back only if the raised ceiling is causing a worse problem than the one it fixed (e.g. a
-- runaway statement by this role now running to 240s), and pair it with the follow-up work named in
-- the forward migration rather than leaving the cron broken.
--
-- OWNERSHIP: no `set role` — `collections` objects are owned by postgres (0084/0085 lesson).

-- ⚠ the LOGIN role, for the same reason the forward migration targets it: GUCs are not
-- inherited through role membership, so resetting the group role `cmd_rollup_writer` is a no-op.
alter role cmd_rollup_writer_login reset statement_timeout;

-- ⚠ THE INDEX CANNOT BE RECREATED BY THIS FILE. `create index concurrently` cannot run inside a
-- transaction block and apply_migration wraps the whole file in one, so running this through
-- apply_migration would fail at this statement. To restore it, run the line below as its OWN
-- single-statement query via execute_sql (autocommit — the 0081/0092/0108 path), outside the
-- :45-:48 refresh window, and note that it will take a SHARE UPDATE EXCLUSIVE-compatible build
-- against 509k rows:
--
--   create index concurrently if not exists cmd_charge_rollup_payer_trgm
--     on collections.cmd_explorer_charge_rollup using gin (primary_payer claims.gin_trgm_ops);
--
-- The opclass MUST be schema-qualified as `claims.gin_trgm_ops` — pg_trgm is installed in the
-- `claims` schema, and a bare `gin_trgm_ops` fails with "operator class does not exist" (0081).
--
-- Before restoring it, re-read 0114's evidence: 2 scans in 111 days, and the planner declined it
-- for the exact query shape it was built for. Restoring it costs 18 MB on every hourly refresh.
